version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ACRONIS_CLIENT_ID=${ACRONIS_CLIENT_ID}
      - ACRONIS_CLIENT_SECRET=${ACRONIS_CLIENT_SECRET}
      - DATACENTER_URL=${DATACENTER_URL}
    volumes:
      - .:/app
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
