version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - ACRONIS_CLIENT_ID=${ACRONIS_CLIENT_ID}
      - ACRONIS_CLIENT_SECRET=${ACRONIS_CLIENT_SECRET}
      - DATACENTER_URL=${DATACENTER_URL}
    volumes:
      - .:/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend

networks:
  default:
    name: acronis-dashboard-network
