version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    env_file:
      - .env
    command: >
      sh -c "
        mkdir -p /app/data &&
        touch /app/data/device_notes.json /app/data/device_status.json /app/data/status_changes.log /app/data/app.log &&
        chown -R nobody:nogroup /app/data &&
        flask run --host=0.0.0.0
      "
